baseurl         = "https://jarettflierl.com/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Jarrett Flierl"
  subtitle    = "creator"

  cover       = "uploads/jarrett-flierl-header.jpg"
  description = "Jarett Flierl's Tester Teaser"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "jarrettflierl"
  fbName = "jarrett.flierl.39"
  githubName = "jarrett-flierl"

  logo = ""
  orgName = "bigFLEXmedia"
  orgWebsite = "https://www.bigflexmedia.com"
  orgDescription = "bigflexmedia"

  author = "Jarrett Flierl"
  authorAvatar = "uploads/jarrett-flierl-profile-picture.jpg"
  authorLocation = "Santa Monica, CA"
  authorWebsite = "https://test.jarrettflierl.com"
  authorDescription = "Creator, Big Flex'r"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Main"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Project"
  url = "/tags/project/"
  weight = 100

[[menu.main]]
  name = "My Life"
  url = "/categories/life/"
  weight = 99

[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 95
